version: "3"
services:
  db:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password0123
    ports:
      - "1433:1433"
  grpc:
    container_name: grpc-todo-server
    build: ./TodoApi-gRPC-Dapper
    stdin_open: true
    tty: true
    ports:
      - "5000:5000"
    links:
      - db
  proxy:
    container_name: grpc-todo-server-proxy
    build: ./Envoy
    ports:
      - "8080:8080"